[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "18.17.1"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"