backend:
    name: git-gateway
    branch: main
    commit_messages:
        create: "Create {{collection}} “{{slug}}”"
        update: "Update {{collection}} “{{slug}}”"
        delete: "Delete {{collection}} “{{slug}}”"
        uploadMedia: "[skip ci] Upload “{{path}}”"
        deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
    - name: "cell-line"
      label: "Cell Lines"
      label_singular: "Cell Line"
      folder: "src/pages/cell-line"
      create: true
      slug: "AICS-{{cell_line_id}}"
      path: "{{slug}}/index"
      identifier_field: "cell_line_id"
      summary: "AICS-{{cell_line_id}} - {{gene}}"
      media_folder: ""
      public_folder: ""
      fields:
          - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "cell-line",
            }
          - {
                label: "ID",
                name: "cell_line_id",
                widget: "number",
                required: true,
            }
          - { label: "name", name: "name", widget: "string", required: false }
          - {
                label: "Status",
                name: "status",
                widget: "select",
                options: ["in progress", "done"],
                default: "in progress",
                required: true,
            }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - {
                label: "Thumbnail Image",
                name: "thumbnail_image",
                widget: "image",
                required: false,
            }
          - {
                label: "Clone Number",
                name: "clone_number",
                widget: "number",
                valueType: int,
                required: false,
            }
          - {
                label: "Parent line ID (leave as 0 for 'WTC')",
                name: "parental_line",
                widget: "number",
                default: 0,
                required: true,
            }
          - {
                label: "Gene",
                name: "gene",
                widget: "relation",
                collection: "gene-name",
                search_fields: ["symbol", "name", "protein", "structure"],
                value_field: "symbol",
                display_fields: ["symbol"],
                required: false,
            }
          - {
                label: "Allele Count",
                name: "allele_count",
                widget: "select",
                options: ["mono", "bi"],
                required: false,
            }

          - {
                label: "Tag Location",
                name: "tag_location",
                widget: "select",
                multiple: true,
                options: ["C-terminus", "N-terminus"],
                required: false,
            }
          - {
                label: "Fluorescent Tag",
                name: "fluorescent_tag",
                widget: "select",
                multiple: true,
                options: ["mEGFP", "EGFP", "mTagRFP-T", "TagBFP", "HaloTag"],
                required: false,
            }
          - {
                label: "Linker",
                name: "linker",
                widget: "string",
                required: false,
            }
          - {
                label: "Order Link",
                name: "order_link",
                widget: "string",
                required: false,
            }
    - name: "disease-cell-line"
      label: "Disease Cell Lines"
      label_singular: "Disease Cell Line"
      folder: "src/pages/disease-cell-line"
      create: true
      slug: "AICS-{{cell_line_id}}"
      path: "{{slug}}/index"
      identifier_field: "cell_line_id"
      summary: "AICS-{{cell_line_id}} - {{disease}}"
      media_folder: ""
      public_folder: ""
      fields:
          - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "disease-cell-line",
            }
          - {
                label: "ID",
                name: "cell_line_id",
                widget: "number",
                required: true,
            }
          - {
                label: "Disease",
                name: "disease",
                widget: "relation",
                collection: "disease",
                search_fields: ["name"],
                value_field: "name",
            }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "SNP", name: "snp", widget: string }
          - {
                label: "Parent line",
                name: "parental_line",
                widget: "relation",
                collection: "cell-line",
                search_fields: ["cell_line_id"],
                value_field: "cell_line_id",
            }
          - {
                label: "Status",
                name: "status",
                widget: "select",
                options: ["in progress", "done"],
                default: "in progress",
                required: true,
            }
          - {
                label: "Clones",
                name: "clones",
                widget: list,
                fields:
                    [
                        {
                            label: "Clone number",
                            name: "clone_number",
                            widget: "number",
                            required: false,
                        },
                        {
                            label: "Clone Type",
                            name: "type",
                            widget: "select",
                            options: ["Mutant", "Control"],
                        },
                        {
                            label: "Transfection Replicate",
                            name: "transfection_replicate",
                            widget: "string",
                            required: false,
                        },
                        {
                            label: "Genotype",
                            name: "genotype",
                            widget: "string",
                            required: false,
                        },
                    ],
            }
          - {
                label: "Order Link",
                name: "order_link",
                widget: "string",
                required: false,
            }
          - {
                label: "Certificate of Analysis",
                name: "certificate_of_analysis",
                widget: "file",
                required: false,
            }
          - {
                label: "hPSCreg Certificate",
                name: "hPSCreg_certificate_link",
                widget: "file",
                required: false,
            }
          - {
                label: "Image and Video Carousel",
                name: "images_and_videos",
                widget: "object",
                required: false,
                fields:
                    [
                        {
                            label: "Images",
                            name: "images",
                            widget: "list",
                            fields:
                                [
                                    {
                                        label: "Image",
                                        name: "image",
                                        widget: "image",
                                    },
                                    {
                                        label: "Caption",
                                        name: "caption",
                                        widget: "string",
                                    },
                                ],
                        },
                        {
                            label: "Videos",
                            name: "videos",
                            widget: "list",
                            fields:
                                [
                                    {
                                        label: "Video",
                                        name: "video",
                                        widget: "file",
                                    },
                                    {
                                        label: "Caption",
                                        name: "caption",
                                        widget: "string",
                                    },
                                ],
                        },
                    ],
            }
          - {
                label: "Stem Cell Characteristics",
                name: "stem_cell_characteristics",
                widget: "list",
                required: false,
                collapsed: true,
                fields:
                    [
                        {
                            label: "Clone number",
                            name: "clone_number",
                            widget: "number",
                            required: false,
                        },
                        {
                            label: "Troponin T, % Positive Cells(n)",
                            name: "positive_cells",
                            widget: "number",
                            required: false,
                        }
                    ],
            }
    - name: "gene-name"
      label: "Gene and structures names"
      folder: "src/pages/gene-names"
      slug: "{{symbol}}"
      create: true # Allow users to create new documents in this collection
      fields: # The fields each document in this collection have
          - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "gene-name",
            }
          - {
                label: "Gene Symbol",
                name: "symbol",
                widget: "string",
                required: true,
            }
          - {
                label: "Gene Name",
                name: "name",
                widget: "string",
                required: true,
            }
          - {
                label: "Protein",
                name: "protein",
                widget: "string",
                required: false,
            }
          - {
                label: "Structure",
                name: "structure",
                widget: "string",
                required: false,
            }
          - label: "Isoforms"
            name: "isoforms"
            widget: "list"
            required: false
            fields:
                - { label: "Gene name", name: "gene_name", widget: "string" }
                - { label: "Isoforms", name: "isoforms", widget: "list" }
    - name: "disease"
      label: "Modeled diseases"
      folder: "src/pages/diseases"
      slug: "{{name}}"
      create: true # Allow users to create new documents in this collection
      fields: # The fields each document in this collection have
          - {
                label: "Template Key",
                name: "templateKey",
                widget: "hidden",
                default: "disease",
            }
          - { label: "Name", name: "name", widget: string }
          - {
                label: "Gene",
                name: "gene",
                widget: "relation",
                collection: "gene-name",
                search_fields: ["symbol", "name", "protein", "structure"],
                value_field: "symbol",
                display_fields: ["symbol", "protein", "structure"],
            }
          - {
                label: "Status",
                name: "status",
                widget: "select",
                options: ["Coming soon", "Available"],
                default: "Coming soon",
                required: true,
            }
          - {
                label: "Acknowledgements",
                name: "acknowledgements",
                widget: "markdown",
            }
    - name: "pages"
      label: "Pages"
      files:
          - file: "src/pages/index.md"
            label: "Landing Page"
            name: "index"
            fields:
                - {
                      label: "Template Key",
                      name: "templateKey",
                      widget: "hidden",
                      default: "index-page",
                  }
                - { label: Title, name: title, widget: string }
                - { label: Image, name: image, widget: image }
                - { label: Subtitle, name: subtitle, widget: string }
                - {
                      label: Mainpitch,
                      name: main_pitch,
                      widget: object,
                      fields:
                          [
                              { label: Title, name: title, widget: string },
                              {
                                  label: Description,
                                  name: description,
                                  widget: text,
                              },
                          ],
                  }
                - {
                      label: Products,
                      name: products,
                      widget: list,
                      fields:
                          [
                              { label: Text, name: text, widget: text },
                              { label: Image, name: image, widget: image },
                          ],
                  }

          - file: "src/pages/disease-catalog/index.md"
            label: "Disease Cell Line Catalog"
            name: "disease-catalog"
            fields:
                - {
                      label: "Template Key",
                      name: "templateKey",
                      widget: "hidden",
                      default: "disease-catalog",
                  }
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Body", name: "body", widget: "markdown" }
                - {
                      label: Main,
                      name: main,
                      widget: object,
                      fields:
                          [
                              { label: Heading, name: heading, widget: string },
                              {
                                  label: Subheading,
                                  name: subheading,
                                  widget: string,
                              },

                              {
                                  label: Description,
                                  name: description,
                                  widget: markdown,
                              },
                          ],
                  }
                - {
                      label: "Coriell Image",
                      name: "coriell_image",
                      widget: "image",
                  }
                - {
                      label: "Coriell Link",
                      name: "coriell_link",
                      widget: "string",
                  }
                - {
                      label: "Footer text",
                      name: "footer_text",
                      widget: "markdown",
                  }
